---
#packages for lamp
package_name:
  - mysql-server
  - python-mysqldb

#variable for mysql
mysql_db: "database"
mysql_user: ""

###################
--- 
- 
  become: true
  hosts: all

  tasks: 
    -       
      name: "Push command"
      ansible.builtin.command: "show cdp neighbors"
      register: cdpneighbor
    - 
      debug: var=cdpneighbor.stdout_lines

    - 
      name: copy the output to a local file
      copy:
        content: "{{ cdpneighbor.stdout_lines }}"
        dest: "/home/command.json"
      delegate_to: localhost

    - 
      name: Affiche un trie dans le json
      debug: msg="{{ command.json | json_query(jmesquery) }}"
      vars:
        jmesquery: "[*].{Name: name, Email: email, Phone: phone, CompanyName: company.name, WebSite: website, City: address.city}"    










#######################

- name: Start mysql
  service:
    name: mysql
    state: started
    
- name: Create database
  mysql_db:
    name: "{{ database }}"
    become: yes

- name: run mysql_upgrade
  shell: "mysql_upgrade -u {{mysql_user}} -p {{mysql_password }}"

ansible-playbook upgrade.yml --extra-vars "mysql_user=iven mysql_pass=Passw0rd"
